apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:       #It helps in reducing the typing kubectl apply -f yaml files. it looks for all the yaml files in 'infra/k8s/'.
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: akashsantact123/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: akashsantact123/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: akashsantact123/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: akashsantact123/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: akashsantact123/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: akashsantact123/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .